### ISSUE TITLE
calendar won't start

### ISSUE THREAD

**Issue by skotzko** [Aupajo/almanack#20]
Following the tutorial and unable to start up almanack. Got as fas as running `almanack start`, then I get this error:

```
<calendar dir>/config.ru:9:in `block (2 levels) in <main>': undefined method `cache_responses=' for #<Almanack::Configuration:0x007fd6d411f820> (NoMethodError)
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/almanack-1.0.5/lib/almanack.rb:19:in `config'
	from /Users/andrew/projects/applied-invention/almanack/fish/config.ru:3:in `block in <main>'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from /Users/andrew/projects/applied-invention/almanack/fish/config.ru:in `new'
	from /Users/andrew/projects/applied-invention/almanack/fish/config.ru:in `<main>'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/bin/rackup:22:in `load'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/bin/rackup:22:in `<main>'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/andrew/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Ruby version:

```
$ ruby --version
> ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

**Comment by skotzko** [comment]
I figured out what this was. I was creating the calendar (via `almanack new testCal`) inside the `almanack` directory that I cloned the repo from. When I create the calendar in any other directory using the CLI, it works fine.
